spring:
  application:
    name: gamefound-campaign-notifier

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health