spring:
  application:
    name: gamefound-campaign-notifier

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  servlet:
    context-path: /api

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health

bgg:
  api:
    base-url: https://boardgamegeek.com/xmlapi2
    token: ${BGG_API_TOKEN}

gamefound:
  api:
    base-url: https://gamefound.com